server:
  port: 4976
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/symon_portal
    username: symon
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: symon-portal
